#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the dbx project: https://github.com/tomeichlersmith/dbx
#
# Copyright (C) 2021 dbx contributors
#
# dbx is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# dbx is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dbx; if not, see <http://www.gnu.org/licenses/>.

dbx_version=0.0.0

# POSIX
set -o errexit
set -o nounset

# create a new dev box
dbx-create() {
}

# enter a dev box
dbx-enter() {
}

# run the input command in the box
dbx-run() {
}

# print a help
dbx-help() {
}

case $1 in
  create|enter|run|help)
    dbx-${1} ${@:2}
    exit $?
    ;;
  *)
    dbx-${DBX_DEFAULT:-run} $@
    exit $?
    ;;
esac
