#!/usr/bin/sh

# check if we can open xeyes and view it from denv
#   using test gui image on GitHub Container Registry
#   we built which definitely has xeyes in it
main() {
  _run_gui_test_dir="$(cd -- "$(dirname -- "$0")" && pwd)"
  _denv_dir="$(cd -- "${_run_gui_test_dir}/../../" && pwd)"
  _denv="${_denv_dir}/denv"
  _test_image="ghcr.io/tomeichlersmith/denv-test-gui-image:latest"

  # need to accomodate mktemp on either GNU (left) or BSD (right)
  test_d=$(mktemp -d 2> /dev/null || mktemp -d -t 'denv-test-gui-tmpdir')
  
  cd "${test_d}" || return 1
  "${_denv}" init --clean-env "${_test_image}" || return 2
  "${_denv}" xeyes || return 3
  cd || return 4
  rm -rf "${test_d}"
}

main
