#!/bin/sh
# build the docs website
# DEPENDENCIES
#   mdbook
#   man
#   ul
#   aha

set -o nounset
set -o errexit

# convert a man page into a corresponding html page
#
# We use the '.md' suffix rather than '.html' so that mdbook still
# processes the html into its own style with the side bar and header.
mkdir -p docs/src/manual
for man_page in man/man1/*; do
  page_name="$(basename "${man_page}")"
  output_file="docs/src/manual/${page_name}.md"
  man -Thtml "${man_page}" > "${output_file}"
done

cd docs
mdbook build
