#!/bin/sh

if ! command -v pandoc; then
	echo '
Please install "pandoc". This tool is needed to convert markdown to man pages.
This tool is needed to convert files under docs/usage into man pages for the
installation.
'
	exit 1
fi

_translate() {
  man_page="$1"  
  pandoc \
    --standalone \
    --metadata title="DENV" \
    --metadata section=1 \
    --metadata header="User Manual" \
    --metadata footer="denv" \
  	--metadata date="$(date +"%b %Y")" \
    --to man docs/src/manual/${man_page}.md \
    -o man/man1/${man_page}.1
}

for page in denv denv-init denv-config
do
  _translate "${page}"
done

