#!/bin/sh

set -o errexit
set -o nounset

# Assume the environment variables MDBOOK_VERSION and MDBOOK_ADMONISH_VERSION are set

# Download a tar ball and then unpack it into a destination
# Arguments
#   1 - URL for the .tar.gz to download
#   2 - target directory to unpack into
download() {
  wget -q -O - "${1}" | tar -xz --directory "${2}"
}

help() {
  cat <<\HELP

 USAGE:
  ./.github/install-mdbook [target]

 ARGUMENTS:
  target : directory to download mdbook and mdbook-admonish into

 ENVIRONMENT:
  We assume that MDBOOK_VERSION and MDBOOK_ADMONISH_VERSION are set
  to the desired versions like how it is done in the CI workflow.

HELP
}

target="${HOME}/.local/bin"
while [ "${#}" -gt 0 ]; do
  case "${1}" in
    -h|--help)
      help
      exit 0
      ;;
    *)
      target="${1}"
      ;;
  esac
  shift
done

mkdir -p "${target}"
download \
  https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
  "${target}"
download \
  https://github.com/tommilligan/mdbook-admonish/releases/download/v${MDBOOK_ADMONISH_VERSION}/mdbook-admonish-v${MDBOOK_ADMONISH_VERSION}-x86_64-unknown-linux-gnu.tar.gz \
  "${target}"
