#!/bin/sh

set -o nounset
set -o errexit

# pre-process the man pages into html with groff
for f in man/man1/*; do
  groff \
    "${f}" \
    -mandoc \
    -Thtml \
    > "docs/src/manual/$(basename "${f}").html"
done

# go into the docs directory
cd docs

# run mdbook there
command mdbook $@
