#!/bin/sh
# testing script for denv, should not be installed with it

# POSIX
set -o errexit
set -o nounset
if [ -n "${DENV_DEBUG+x}" ]; then
  set -o xtrace
fi

_denv_info() {
  printf "\033[32;1m INFO: \033[0m\033[32m%s\n" "$1"
  shift
  while [ "$#" -gt "0" ]; do
    printf '       %s\n' "$1"
    shift
  done
  printf "\033[0m"
}

# print each argument on its own line with the first line
# prefixed with "ERROR: ".
_denv_error() {
  printf >&2 "\033[1;31mERROR: \033[0m\033[31m%s\n" "$1"
  shift
  while [ "$#" -gt "0" ]; do
    printf >&2 "       %s\n" "$1"
    shift
  done
  printf >&2 "\033[0m"
}

help() {
  cat <<\HELP

  ./ci/test [-h,--help] [--preserve {all,none,error}] RUNNER [RUNNER1 ...]

 DESCRIPTION

  Test denv with the specified runner(s).

  This is just a wrapper script around running bats which defines some
  helpful environment variables using the correct names.

 ARGUMENTS
  RUNNER : the name for a container runner that denv should test with
           if more than one is provided, test them all in sequence.
           The special runner 'norunner' will test as much of denv as
           possible without a runner installed.

 OPTIONS
  -h,--help  : print this help and exit
  --preserve : choose if we should remove the temporary directories made
               during testing ("none"), save all of the ("all"), or only
               save the ones that are from errors ("error"). The temp
               directories created by bats correspond to the file name
               and test index and are inside the system temp directory
               (TMPDIR or /tmp if undefined).

HELP
}

if [ "$#" -eq "0" ]; then
  help
  exit 0
fi

runners=""
while [ "$#" -gt "0" ]; do
  case "$1" in
    help|-h|--help)
      help
      exit 0
      ;;
    --preserve)
      shift
      if [ -z "${1:-}" ]; then
        _denv_error "--preserve requires an argument {all,none,error} after it"
      fi
      case "${1}" in
        all)
          export BATSLIB_TEMP_PRESERVE=1
          ;;
        error)
          export BATSLIB_TEMP_PRESERVE_ON_FAILURE=1
          ;;
        none)
          ;;
        *)
          _denv_error "Unrecognized --preserve argument '$1'." \
            "Not one of {all,none,error}."
          exit 1
      esac
      ;;
    -*)
      _denv_error "Unrecognized option '$1'."
      exit 1
      ;;
    *)
      runners="${runners} $1"
      ;;
  esac
  shift
done

if [ -z "${runners}" ]; then
  _denv_error "Need to specify at least one runner to test"
  exit 1
fi

for runner in ${runners}; do
  filter_tags=""
  case "${runner}" in
    norunner)
      filter_tags="--filter-tags norunner"
      ;;
    docker|podman)
      filter_tags="--filter-tags !apptainer"
      ;;
    *)
      filter_tags=""
      ;;
  esac
  _denv_info "Testing denv with '${runner}' ${filter_tags}"
  # shellcheck disable=SC2086
  DENV_RUNNER="${runner}" ./test/bats/bin/bats ${filter_tags} test/
done
