#!/bin/sh
# testing script for denv, should not be installed with it
#   set DENV_RUNNER environment variable to the runner to use with denv
#   for the testing otherwise the test suite will exit before any testing

# POSIX
set -o errexit
set -o nounset
#set -o xtrace

./test/bats/bin/bats test/
