
name: Test Image Build

on:
  push:
    paths:
      - '.github/workflows/build-test-image.yml'
      - 'test/gui/image/**'
    branches:
      - '**'
    tags:
      - '*.*.*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: tomeichlersmith/denv-test-gui-image

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    -
      name: Setup QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Get tag and labels for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: latest
    - 
      name: Get Build Context
      uses: actions/checkout@v3
    -
      name: Build the Image
      uses: docker/build-push-action@v6
      with:
        context: test/gui/image/
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
